[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
logfile_maxbytes=10MB
loglevel=info

[inet_http_server]
port=0.0.0.0:9007

[rpcinterface:supervisor]
supervisor.rpcinterface_factory=supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://localhost:9007

; MOLA AUV simulation (Stonefish).
[program:01_mola_auv_sim]
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && source /root/ros2_ws/install/setup.bash && source /root/MBARI-vehicles-sim-ros2/stonefish_ws/install/setup.bash && ros2 launch mola_auv_sim mola_auv_sim.launch.py"
autostart=false
autorestart=false
stdout_logfile=/var/log/supervisor/mola_auv_sim.log
stderr_logfile=/var/log/supervisor/mola_auv_sim.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB

; MOLA AUV simulation with keyboard teleop.
[program:02_mola_auv_teleop]
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && source /root/ros2_ws/install/setup.bash && source /root/MBARI-vehicles-sim-ros2/stonefish_ws/install/setup.bash && ros2 launch mola_auv_sim mola_auv_sim_teleop.launch.py"
autostart=false
autorestart=false
stdout_logfile=/var/log/supervisor/mola_auv_teleop.log
stderr_logfile=/var/log/supervisor/mola_auv_teleop.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB

; Ricketts ROV simulation (Stonefish).
[program:03_ricketts_sim]
command=/bin/bash -c "source /opt/ros/jazzy/setup.bash && source /root/ros2_ws/install/setup.bash && source /root/MBARI-vehicles-sim-ros2/stonefish_ws/install/setup.bash && ros2 launch ricketts_sim ricketts_sim.launch.py"
autostart=false
autorestart=false
stdout_logfile=/var/log/supervisor/ricketts_sim.log
stderr_logfile=/var/log/supervisor/ricketts_sim.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
